options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # 1. Extraer variables del TAG
  - name: 'gcr.io/cloud-builders/git'
    id: 'parse-tag'
    entrypoint: 'bash'
    env:
      - 'GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=web-tier-tf@rs-web-tier.iam.gserviceaccount.com'
    args:
      - '-c'
      - |
        echo "Analizando Tag: $TAG_NAME"
        
        # Usamos $$ para que Cloud Build no intente sustituir estas variables
        export ACTION=$$(echo "$TAG_NAME" | cut -d'#' -f1)
        export PROJECT_ID=$$(echo "$TAG_NAME" | cut -d'#' -f2)
        
        echo "Accion detectada: $${ACTION}"
        echo "Proyecto detectado: $${PROJECT_ID}"

        # Validar existencia de la carpeta tras el renombre
        if [ -d "environments/$${PROJECT_ID}" ]; then
          echo "environments/$${PROJECT_ID}" > /workspace/tf_folder
        elif [ -d "$${PROJECT_ID}" ]; then
          echo "$${PROJECT_ID}" > /workspace/tf_folder
        else
          echo "ERROR: No existe la carpeta para $${PROJECT_ID}"
          exit 1
        fi
        
        echo "$${ACTION}" > /workspace/tf_action

  # 2. Ejecutar Terraform
  - name: 'hashicorp/terraform'
    id: 'tf-run'
    entrypoint: 'sh'
    env:
      - 'GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=web-tier-tf@rs-web-tier.iam.gserviceaccount.com'
    args:
      - '-c'
      - |
        # Recuperamos los valores del workspace
        TF_ACTION=$$(cat /workspace/tf_action)
        TF_FOLDER=$$(cat /workspace/tf_folder)
        
        echo "Ejecutando $${TF_ACTION} en $${TF_FOLDER}"
        cd "$${TF_FOLDER}"
        
        terraform init --upgrade
        if [ "$${TF_ACTION}" == "plan" ]; then
          terraform plan
        elif [ "$${TF_ACTION}" == "apply" ]; then
          terraform apply -auto-approve
        fi